// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {util} from '../models';

export function Actions():Promise<util.ActionsType>;

export function Clean():Promise<string>;

export function CopyText():Promise<string>;

export function DownloadAndExtract(arg1:Array<number>,arg2:string):Promise<void>;

export function DownloadAndInstall(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function GetDeviceID():Promise<util.DeviceInfo>;

export function Greet(arg1:string):Promise<string>;

export function InstallFile(arg1:string,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<string>;
