// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {util} from '../models';

export function Actions():Promise<util.ActionsType>;

export function Clean():Promise<string>;

export function GetDeviceID():Promise<util.DeviceInfo>;

export function Greet(arg1:string):Promise<string>;
