// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Actions() {
  return ObfuscatedCall(0, []);
}

export function Clean() {
  return ObfuscatedCall(1, []);
}

export function CopyText() {
  return ObfuscatedCall(2, []);
}

export function DownloadAndExtract(arg1, arg2) {
  return ObfuscatedCall(3, [arg1, arg2]);
}

export function GetDeviceID() {
  return ObfuscatedCall(4, []);
}

export function Greet(arg1) {
  return ObfuscatedCall(5, [arg1]);
}
