// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Actions() {
  return window['go']['main']['App']['Actions']();
}

export function Clean() {
  return window['go']['main']['App']['Clean']();
}

export function GetDeviceID() {
  return window['go']['main']['App']['GetDeviceID']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
