name: Release Linux App

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: '1.0.0'

permissions:
  contents: write

jobs:
  release:
    name: Release Linux App
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/aarch64

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Normalise platform tag
        id: normalise_platform
        shell: bash
        run: |
          tag=$(echo ${{ matrix.platform }} | sed -e 's/\//_/g')
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Normalise platform arch
        id: normalise_platform_arch
        run: |
          if [ "${{ matrix.platform }}" == "linux/amd64" ]; then
            echo "arch=x86_64" >> "$GITHUB_OUTPUT"
            echo "deb_arch=amd64" >> "$GITHUB_OUTPUT"
          elif [ "${{ matrix.platform }}" == "linux/aarch64" ]; then
            echo "arch=aarch64" >> "$GITHUB_OUTPUT"
            echo "deb_arch=arm64" >> "$GITHUB_OUTPUT"
          fi

      - name: Normalise version tag
        id: normalise_version
        shell: bash
        run: |
          if [ "${{ github.event.release.tag_name }}" == "" ]; then
            version=$(echo ${{ github.event.inputs.tag }} | sed -e 's/v//g')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          else
            version=$(echo ${{ github.event.release.tag_name }} | sed -e 's/v//g')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Install wails
        shell: bash
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Ubuntu prerequisites
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libfuse-dev libfuse2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Build frontend assets
        shell: bash
        run: |
          npm install -g npm@9
          jq '.info.productVersion = "${{ steps.normalise_version.outputs.version }}"' wails.json > tmp.json
          mv tmp.json wails.json
          cd frontend
          jq '.version = "${{ steps.normalise_version.outputs.version }}"' package.json > tmp.json
          mv tmp.json package.json
          npm install

      - name: Build wails app for Linux
        shell: bash
        run: |
          CGO_ENABLED=1 wails build -platform ${{ matrix.platform }} -debug \
          -ldflags "-X main.version=v${{ steps.normalise_version.outputs.version }} -X main.gaMeasurementID=${{ secrets.GA_MEASUREMENT_ID }} -X main.gaSecretKey=${{ secrets.LINUX_GA_SECRET }}" \
          -tags webkit2_41 \
          -o jetbrains

      - name: Setup control template
        shell: bash
        run: |
          content=$(cat build/linux/jetbrains_0.0.0_${{ steps.normalise_platform_arch.outputs.deb_arch }}/DEBIAN/control)
          name=$(jq -r '.name' wails.json | tr -d ' ' | tr '[:upper:]' '[:lower:]')
          content=$(echo "$content" | sed -e "s/{{.Name}}/$name/g")
          content=$(echo "$content" | sed -e "s/{{.Info.ProductVersion}}/$(jq -r '.info.productVersion' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.Author.Name}}/$(jq -r '.author.name' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.Author.Email}}/$(jq -r '.author.email' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.Info.Comments}}/$(jq -r '.info.comments' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.libwebkit2gtk.PackageName}}/libwebkit2gtk-4.1-0/g")
          echo $content
          echo "$content" > build/linux/jetbrains_0.0.0_${{ steps.normalise_platform_arch.outputs.deb_arch }}/DEBIAN/control

      - name: Setup app template
        shell: bash
        run: |
          content=$(cat build/linux/jetbrains_0.0.0_${{ steps.normalise_platform_arch.outputs.deb_arch }}/usr/share/applications/jetbrains.desktop)
          content=$(echo "$content" | sed -e "s/{{.Info.ProductName}}/$(jq -r '.info.productName' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.Info.Comments}}/$(jq -r '.info.comments' wails.json)/g")
          echo $content
          echo "$content" > build/linux/jetbrains_0.0.0_${{ steps.normalise_platform_arch.outputs.deb_arch }}/usr/share/applications/jetbrains.desktop

      - name: Package up deb file
        shell: bash
        run: |
          mv build/bin/jetbrains build/linux/jetbrains_0.0.0_${{ steps.normalise_platform_arch.outputs.deb_arch }}/usr/local/bin/
          cd build/linux
          mv jetbrains_0.0.0_${{ steps.normalise_platform_arch.outputs.deb_arch }} "jetbrains_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform_arch.outputs.deb_arch }}"
          sed -i 's/0.0.0/${{ steps.normalise_version.outputs.version }}/g' "jetbrains_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform_arch.outputs.deb_arch }}/DEBIAN/control"
          dpkg-deb --build -Zxz "jetbrains_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform_arch.outputs.deb_arch }}"

      - name: Rename deb
        working-directory: ./build/linux
        run: mv "jetbrains_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform_arch.outputs.deb_arch }}.deb" "jetbrains_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}_webkit2_41.deb"

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.normalise_version.outputs.version }}
          files: |
            ./build/linux/jetbrains_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}_webkit2_41.deb
          token: ${{ secrets.GITHUB_TOKEN }}